#!/bin/sh

# ‹collect› -- Collect a number of samples from a virtual machine.
#
# 	collect [-h] [-o DIR] FLAKE N [MACHINE HOSTNAME]
#
# This script collects ‹N› samples by repeating this procedure:
#   - Start the VM.
#   - Collect information from the VM (systemd version, tpm2 event log, …).
#   - Power off the VM
#   - Collect information from TPM Spy.
#
# To avoid corruption or intereference in the first data point, ensure the
# VM is powered off before running this script.
#
# The results are stored as separate directories in the format
#
# 	$cfg_traces_dst/$FLAKE/$STAMP
#
# where ‹$STAMP› is a date and time of the format 'YYMMDD.HHMMSS.NNNN'.
# If the directory exists (unlikely, but theoretically possible when two
# scripts run ‹date› at exactly the same time), the script fails.
#
# The ‹FLAKE› argument is used only for storing the results into an appropriate
# directory. Use ‹switch $FLAKE› script to actually switch a system to a given
# flake.
#
# To collect data from different machines, one may use ‹MACHINE› and ‹HOSTNAME›
# as optional arguments. In addition, ‹-o DIR› can be specified to override
# ‹$cfg_traces_dst› directory path from ‹config› file.

script_path=$(readlink -f "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

. "$script_bin/common"


usage() {
	echo "usage: $script_name [-o DIR] FLAKE N [MACHINE HOSTNAME]" >&2
}

opt_target_dir=
while getopts "hno:" option; do
	case "${option}" in
	h)
		usage
		exit 0
		;;

	o)
		opt_target_dir="$OPTARG"
		;;

	*)
		usage >&2
		exit 1
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 2 ] && [ "$#" -ne 4 ]; then
	usage >&2
	exit 1
fi

flake="$1"
count="$2"
p_machine="${3:-$cfg_machine}"
p_hostname="${4:-$cfg_hostname}"

target_dir="${opt_target_dir:-$cfg_traces_dst}"/"$flake"
mkdir -p "$target_dir"

for trace_no in $(seq -w 0 "$((count - 1))"); do
	stamp="$(date '+%y%m%d.%H%M%S.%3N')"

	if ! mkdir "$target_dir/$stamp"; then
		die "Trace $trace_no: $stamp: Failed to create output directory"
	fi

	"$script_bin"/collect1 -o "$target_dir/$stamp" "$p_machine" "$p_hostname"
done
