#!/bin/sh

die() {
	echo "$script_name: $*" >&2
	exit 1
}

str_ends_with() {
	test "${1%"$2"}" != "$1"
}

virsh_cmd() {
	virsh --connect "$cfg_qemu_session" "$@"
}

virsh_get_ip() {
	virsh_cmd net-dhcp-leases default | grep "${1:-$cfg_hostname}" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'
}

virsh_is_running() {
	virsh_cmd list --all | grep -qF "${1:-$cfg_machine}" | grep -qF 'running'
}

virsh_is_shutdown() {
	virsh_cmd domstate "${1:-$cfg_machine}" | grep -F "shut off"
}

wait_for() {
	while true; do
		rv=$("$@")

		if [ -n "$rv" ]; then
			echo "$rv"
			return
		fi

		sleep 1
	done
}

virsh_start() {
	_machine="${1:-$cfg_machine}"
	_hostname="${2:-$cfg_hostname}"

	virsh_cmd start "$_machine" >/dev/null

	host_ip=$(wait_for virsh_get_ip "$_hostname")
	until ping -q -c1 -W1 "$host_ip" >/dev/null; do
		sleep 2
	done

	echo "$host_ip"
	unset _machine _hostname
}

run_in_machine() {
	host_ip="$1"
	shift

	ssh -i "$cfg_ssh_key" root@"$host_ip" -- "$@"
}
