#!/bin/sh

# ‹convert› - Convert captured TPMSpy binary dumps to JSON
#
# 	convert [-h]
#
# The script takes no arguments. It searches for ‹tpmspy.bin› files in
# the ‹$cfg_traces_dst› directory and converts them to ‹tpmspy.json›.

script_path=$(readlink -f "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

. "$script_bin/config"
. "$script_bin/common"


usage() {
	echo "usage: $script_name" >&2
}

find_dump() {
	for candidate in "$script_bin/../build/dump/dump"; do
		if [ -x "$candidate" ]; then
			echo "$candidate"
			return
		fi
	done

	# Last resort -- try looking everywhere
	if ! find "$script_bin/.." -type f -name dump -executable | head -n1 | grep '^'; then
		echo "No dump executable found" >&2
		exit 1
	fi
}

while getopts "h" option; do
	case "${option}" in
	h)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	usage >&2
	exit 1
fi

hostname=$(hostname -s)
dump_bin=$(find_dump)

find "$cfg_traces_dst" -type f -name 'tpmspy.bin' -printf '%P\n' | while read -r source; do
	target="${source%.bin}.json"

	if [ ! -f "$cfg_traces_dst/$target" ]; then
		echo "$source -> $target"
		"$dump_bin" --json "$cfg_traces_dst/$source" >"$cfg_traces_dst/$target"
	fi
done
