#!/bin/sh

# ‹convert› - Convert captured TPMSpy binary dumps to JSON
#
# 	convert [-h] [DIR]
#
# The script takes no arguments. It searches for ‹tpmspy.bin› files in
# the ‹DIR› (or ‹$cfg_traces_dst›) directory and converts them to ‹tpmspy.json›.

script_path=$(readlink -f "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

. "$script_bin/common"


usage() {
	echo "usage: $script_name" >&2
}

find_dump() {
	for candidate in "$script_bin/../tpmspy/build/dump/dump"; do
		if [ -x "$candidate" ]; then
			echo "$candidate"
			return
		fi
	done

	# Last resort -- try looking everywhere
	if ! find "$script_bin/.." -type f -name dump -executable | head -n1 | grep '^'; then
		warn "No dump executable found"
		exit 1
	fi
}

while getopts "h" option; do
	case "${option}" in
	h)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
	esac
done

shift $((OPTIND - 1))

if [ "$#" -gt 1 ]; then
	usage >&2
	exit 1
fi

dump_bin=$(find_dump)

dir="${1:-$COLLECT_TRACE_DIR}"
dir="${dir:-$cfg_traces_dst}"

find "$dir" -type f -name 'tpmspy.bin' -printf '%P\n' | while read -r source; do
	target="${source%.bin}.json"

	if [ ! -f "$dir/$target" ]; then
		echo "$source -> $target"
		"$dump_bin" --json "$dir/$source" >"$dir/$target"

		if [ -f "$dir/$target" ] && ! [ -s "$dir/$target" ]; then
			warn "$dir/$target: File is empty"
			unlink "$dir/$target"
		fi
	fi
done
