#!/bin/sh

# ‹flakes› -- Get a list of available flakes from a VM.
#
# 	flakes [-h] [-k]
#
# This script starts up a VM and prints a list of flakes available.
#
# The script tries to preserve the shutdown/running state of the machine. If
# the machine was running already, the script leaves it be. If the machine had
# to be started, the script will shut it before it ends. The option ‹-k›
# instructs the script to keep the machine running in any case.

script_path=$(readlink -f "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

. "$script_bin/common"


usage() {
	echo "usage: ${script_name} [-k]"
}

opt_keep=0
while getopts "hk" option; do
	case "${option}" in
	h)
		usage
		exit 0
		;;
	k)
		opt_keep=1
		;;
	*)
		usage >&2
		exit 1
	esac
done

shift $((OPTIND - 1))

if [ "$#" -ne 0 ]; then
	usage >&2
	exit 1
fi

if [ -z "$cfg_flakes" ]; then
	warn "\$cfg_flakes is not configured"
	exit 1
fi

if virsh_is_running "$cfg_machine"; then
	was_running=1
fi

host_ip=$(virsh_start "$cfg_machine" "$cfg_hostname") >&2

run_in_machine "$host_ip" nix eval "$cfg_flakes#nixosConfigurations" --apply 'builtins.attrNames' --json \
	| jq -r '.[]'

if [ "$opt_keep" -eq 0 ] && [ ! -z "$was_running" ]; then
	virsh_cmd shutdown "$cfg_machine" >&2
	wait_for virsh_is_shutdown "$cfg_machine" >&2
fi
