#!/bin/sh

# ‹setup› -- Build selected flakes
#
# 	setup [-h] [-k] FLAKES…
#
# For one or more flakes given as ‹FLAKES…›, the script starts up the VM
# and rebuilds the configuration for each flake if not available.
#
# Unless ‹-k› is specified as an option, the script shuts down the VM
# afterwards.
#
# Note that this script requires Nix Flakes feature to be available in the
# system running in the VM. Thus it is best to ensure that the system is
# switched to the newest Nix available beforehand, e.g. by using the ‹switch›
# script.

script_path=$(readlink -f "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

. "$script_bin/config"
. "$script_bin/common"


usage() {
	echo "usage: ${script_name} [-k] FLAKES…"
}

opt_keep=0
while getopts "hk" option; do
	case "${option}" in
	h)
		usage
		exit 0
		;;
	k)
		opt_keep=1
		;;
	*)
		usage >&2
		exit 1
	esac
done

shift $((OPTIND - 1))

if [ "$#" -lt "1" ]; then
	usage >&2
	exit 1
fi

host_ip=$(virsh_start "$cfg_machine" "$cfg_hostname")

for flake in "$@"; do
	run_in_machine "$host_ip" <<-SSH
		cd "${cfg_flakes}"
		if [ -L "${flake}.result" ]; then
			exit 0
		fi

		nixos-rebuild build --flake ".#${flake}"

		if ! [ -L result ]; then
			echo "BUG: File 'result' is not a symlink" >&2
			exit 1
		fi

		mv -T result "${flake}.result"
		SSH

done

if [ "$opt_keep" -eq 0 ]; then
	virsh_cmd shutdown "$cfg_machine" >&2
	wait_for virsh_is_shutdown "$cfg_machine" >&2
fi
