#!/usr/bin/perl

use v5.40;

die "usage: $0 FILENAME\n"
	if @ARGV != 1;

my ($filename) = @ARGV;

my $prefix = $filename;
$prefix =~ s/\.\w+$//;

open my $input, '<:encoding(utf-8)', $filename
	or die "$filename: $!";

my ($output, $target);
while (my $line = readline $input) {
	chomp $line;

	next if !defined $output && $line =~ /^\s*$/;

	if ($line =~ /CHANGES WITH\s*([0-9\.]+)/) {
		close $output if defined $output;
		my $version = $1;

		$target = "$prefix-$version.txt";
		open $output, '>:encoding(utf-8)', $target
			or die "$target: $!";

		say "$target";
	}

	if (!defined $output) {
		say STDERR "$filename: $.: '$line' ignored";
		next;
	}

	say { $output } $line;
}
