FROM alpine:3.23

# TPMSpy
RUN apk add pkgconfig
RUN apk add make
RUN apk add meson
RUN apk add gcc
RUN apk add g++
RUN apk add libev libev-dev
RUN apk add json-c json-c-dev
RUN apk add libsodium libsodium-dev
RUN apk add linux-headers
RUN apk add swtpm swtpm-dev
RUN apk add tpm2-tools
RUN apk add tpm2-tss tpm2-tss-dev
RUN apk add libbsd libbsd-dev

# Python
# https://stackoverflow.com/questions/62554991/how-do-i-install-python-on-alpine-linux
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3
RUN ln -sf python3 /usr/bin/python
RUN apk add py3-matplotlib
RUN apk add py3-yaml

# Perl
RUN apk add perl perl-dev
RUN perl -MCPAN -e 'CPAN::Shell->notest("install", "Text::Xslate")'
RUN apk add perl-yaml-pp

CMD ["/bin/sh", "-i"]
